// coverage:ignore-file
// opencv_dart - OpenCV bindings for Dart language
//    License: Apache-2.0 https://github.com/hybridgroup/gocv/blob/release/LICENSE.txt
// Author: Rainyl
// License: Apache-2.0
// Date: 2024/01/28

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint

/// Mapping from Dart function name to native symbol name.
const recordUseMapping = {
  'cv_aruco_Dictionary_close': 'cv_aruco_Dictionary_close',
  'cv_aruco_Dictionary_create': 'cv_aruco_Dictionary_create',
  'cv_aruco_Dictionary_create_1': 'cv_aruco_Dictionary_create_1',
  'cv_aruco_Dictionary_generateImageMarker': 'cv_aruco_Dictionary_generateImageMarker',
  'cv_aruco_Dictionary_getDistanceToId': 'cv_aruco_Dictionary_getDistanceToId',
  'cv_aruco_Dictionary_get_bytesList': 'cv_aruco_Dictionary_get_bytesList',
  'cv_aruco_Dictionary_get_markerSize': 'cv_aruco_Dictionary_get_markerSize',
  'cv_aruco_Dictionary_get_maxCorrectionBits': 'cv_aruco_Dictionary_get_maxCorrectionBits',
  'cv_aruco_Dictionary_identify': 'cv_aruco_Dictionary_identify',
  'cv_aruco_Dictionary_set_bytesList': 'cv_aruco_Dictionary_set_bytesList',
  'cv_aruco_Dictionary_set_markerSize': 'cv_aruco_Dictionary_set_markerSize',
  'cv_aruco_Dictionary_set_maxCorrectionBits': 'cv_aruco_Dictionary_set_maxCorrectionBits',
  'cv_aruco_arucoDetector_close': 'cv_aruco_arucoDetector_close',
  'cv_aruco_arucoDetector_create': 'cv_aruco_arucoDetector_create',
  'cv_aruco_arucoDetector_create_1': 'cv_aruco_arucoDetector_create_1',
  'cv_aruco_arucoDetector_detectMarkers': 'cv_aruco_arucoDetector_detectMarkers',
  'cv_aruco_charucoBoard_checkCharucoCornersCollinear': 'cv_aruco_charucoBoard_checkCharucoCornersCollinear',
  'cv_aruco_charucoBoard_close': 'cv_aruco_charucoBoard_close',
  'cv_aruco_charucoBoard_create': 'cv_aruco_charucoBoard_create',
  'cv_aruco_charucoBoard_create_1': 'cv_aruco_charucoBoard_create_1',
  'cv_aruco_charucoBoard_create_2': 'cv_aruco_charucoBoard_create_2',
  'cv_aruco_charucoBoard_generateImage': 'cv_aruco_charucoBoard_generateImage',
  'cv_aruco_charucoBoard_getChessboardCorners': 'cv_aruco_charucoBoard_getChessboardCorners',
  'cv_aruco_charucoBoard_getChessboardSize': 'cv_aruco_charucoBoard_getChessboardSize',
  'cv_aruco_charucoBoard_getIds': 'cv_aruco_charucoBoard_getIds',
  'cv_aruco_charucoBoard_getLegacyPattern': 'cv_aruco_charucoBoard_getLegacyPattern',
  'cv_aruco_charucoBoard_getMarkerLength': 'cv_aruco_charucoBoard_getMarkerLength',
  'cv_aruco_charucoBoard_getObjPoints': 'cv_aruco_charucoBoard_getObjPoints',
  'cv_aruco_charucoBoard_getSquareLength': 'cv_aruco_charucoBoard_getSquareLength',
  'cv_aruco_charucoBoard_matchImagePoints': 'cv_aruco_charucoBoard_matchImagePoints',
  'cv_aruco_charucoBoard_setLegacyPattern': 'cv_aruco_charucoBoard_setLegacyPattern',
  'cv_aruco_charucoDetectorParameters_close': 'cv_aruco_charucoDetectorParameters_close',
  'cv_aruco_charucoDetectorParameters_create': 'cv_aruco_charucoDetectorParameters_create',
  'cv_aruco_charucoDetectorParameters_get_cameraMatrix':
      'cv_aruco_charucoDetectorParameters_get_cameraMatrix',
  'cv_aruco_charucoDetectorParameters_get_checkMarkers':
      'cv_aruco_charucoDetectorParameters_get_checkMarkers',
  'cv_aruco_charucoDetectorParameters_get_distCoeffs': 'cv_aruco_charucoDetectorParameters_get_distCoeffs',
  'cv_aruco_charucoDetectorParameters_get_minMarkers': 'cv_aruco_charucoDetectorParameters_get_minMarkers',
  'cv_aruco_charucoDetectorParameters_get_tryRefineMarkers':
      'cv_aruco_charucoDetectorParameters_get_tryRefineMarkers',
  'cv_aruco_charucoDetectorParameters_set_cameraMatrix':
      'cv_aruco_charucoDetectorParameters_set_cameraMatrix',
  'cv_aruco_charucoDetectorParameters_set_checkMarkers':
      'cv_aruco_charucoDetectorParameters_set_checkMarkers',
  'cv_aruco_charucoDetectorParameters_set_distCoeffs': 'cv_aruco_charucoDetectorParameters_set_distCoeffs',
  'cv_aruco_charucoDetectorParameters_set_minMarkers': 'cv_aruco_charucoDetectorParameters_set_minMarkers',
  'cv_aruco_charucoDetectorParameters_set_tryRefineMarkers':
      'cv_aruco_charucoDetectorParameters_set_tryRefineMarkers',
  'cv_aruco_charucoDetector_close': 'cv_aruco_charucoDetector_close',
  'cv_aruco_charucoDetector_create_1': 'cv_aruco_charucoDetector_create_1',
  'cv_aruco_charucoDetector_create_2': 'cv_aruco_charucoDetector_create_2',
  'cv_aruco_charucoDetector_create_3': 'cv_aruco_charucoDetector_create_3',
  'cv_aruco_charucoDetector_create_4': 'cv_aruco_charucoDetector_create_4',
  'cv_aruco_charucoDetector_detectBoard': 'cv_aruco_charucoDetector_detectBoard',
  'cv_aruco_charucoDetector_detectDiamonds': 'cv_aruco_charucoDetector_detectDiamonds',
  'cv_aruco_charucoDetector_getBoard': 'cv_aruco_charucoDetector_getBoard',
  'cv_aruco_charucoDetector_getCharucoParameters': 'cv_aruco_charucoDetector_getCharucoParameters',
  'cv_aruco_charucoDetector_getDetectorParameters': 'cv_aruco_charucoDetector_getDetectorParameters',
  'cv_aruco_charucoDetector_getRefineParameters': 'cv_aruco_charucoDetector_getRefineParameters',
  'cv_aruco_charucoDetector_setBoard': 'cv_aruco_charucoDetector_setBoard',
  'cv_aruco_charucoDetector_setCharucoParameters': 'cv_aruco_charucoDetector_setCharucoParameters',
  'cv_aruco_charucoDetector_setDetectorParameters': 'cv_aruco_charucoDetector_setDetectorParameters',
  'cv_aruco_charucoDetector_setRefineParameters': 'cv_aruco_charucoDetector_setRefineParameters',
  'cv_aruco_detectorParameters_close': 'cv_aruco_detectorParameters_close',
  'cv_aruco_detectorParameters_create': 'cv_aruco_detectorParameters_create',
  'cv_aruco_detectorParameters_get_adaptiveThreshConstant':
      'cv_aruco_detectorParameters_get_adaptiveThreshConstant',
  'cv_aruco_detectorParameters_get_adaptiveThreshWinSizeMax':
      'cv_aruco_detectorParameters_get_adaptiveThreshWinSizeMax',
  'cv_aruco_detectorParameters_get_adaptiveThreshWinSizeMin':
      'cv_aruco_detectorParameters_get_adaptiveThreshWinSizeMin',
  'cv_aruco_detectorParameters_get_adaptiveThreshWinSizeStep':
      'cv_aruco_detectorParameters_get_adaptiveThreshWinSizeStep',
  'cv_aruco_detectorParameters_get_aprilTagCriticalRad':
      'cv_aruco_detectorParameters_get_aprilTagCriticalRad',
  'cv_aruco_detectorParameters_get_aprilTagDeglitch': 'cv_aruco_detectorParameters_get_aprilTagDeglitch',
  'cv_aruco_detectorParameters_get_aprilTagMaxLineFitMse':
      'cv_aruco_detectorParameters_get_aprilTagMaxLineFitMse',
  'cv_aruco_detectorParameters_get_aprilTagMaxNmaxima': 'cv_aruco_detectorParameters_get_aprilTagMaxNmaxima',
  'cv_aruco_detectorParameters_get_aprilTagMinClusterPixels':
      'cv_aruco_detectorParameters_get_aprilTagMinClusterPixels',
  'cv_aruco_detectorParameters_get_aprilTagMinWhiteBlackDiff':
      'cv_aruco_detectorParameters_get_aprilTagMinWhiteBlackDiff',
  'cv_aruco_detectorParameters_get_aprilTagQuadDecimate':
      'cv_aruco_detectorParameters_get_aprilTagQuadDecimate',
  'cv_aruco_detectorParameters_get_aprilTagQuadSigma': 'cv_aruco_detectorParameters_get_aprilTagQuadSigma',
  'cv_aruco_detectorParameters_get_cornerRefinementMaxIterations':
      'cv_aruco_detectorParameters_get_cornerRefinementMaxIterations',
  'cv_aruco_detectorParameters_get_cornerRefinementMethod':
      'cv_aruco_detectorParameters_get_cornerRefinementMethod',
  'cv_aruco_detectorParameters_get_cornerRefinementMinAccuracy':
      'cv_aruco_detectorParameters_get_cornerRefinementMinAccuracy',
  'cv_aruco_detectorParameters_get_cornerRefinementWinSize':
      'cv_aruco_detectorParameters_get_cornerRefinementWinSize',
  'cv_aruco_detectorParameters_get_detectInvertedMarker':
      'cv_aruco_detectorParameters_get_detectInvertedMarker',
  'cv_aruco_detectorParameters_get_errorCorrectionRate':
      'cv_aruco_detectorParameters_get_errorCorrectionRate',
  'cv_aruco_detectorParameters_get_markerBorderBits': 'cv_aruco_detectorParameters_get_markerBorderBits',
  'cv_aruco_detectorParameters_get_maxErroneousBitsInBorderRate':
      'cv_aruco_detectorParameters_get_maxErroneousBitsInBorderRate',
  'cv_aruco_detectorParameters_get_maxMarkerPerimeterRate':
      'cv_aruco_detectorParameters_get_maxMarkerPerimeterRate',
  'cv_aruco_detectorParameters_get_minCornerDistanceRate':
      'cv_aruco_detectorParameters_get_minCornerDistanceRate',
  'cv_aruco_detectorParameters_get_minDistanceToBorder':
      'cv_aruco_detectorParameters_get_minDistanceToBorder',
  'cv_aruco_detectorParameters_get_minMarkerDistanceRate':
      'cv_aruco_detectorParameters_get_minMarkerDistanceRate',
  'cv_aruco_detectorParameters_get_minMarkerPerimeterRate':
      'cv_aruco_detectorParameters_get_minMarkerPerimeterRate',
  'cv_aruco_detectorParameters_get_minOtsuStdDev': 'cv_aruco_detectorParameters_get_minOtsuStdDev',
  'cv_aruco_detectorParameters_get_perspectiveRemoveIgnoredMarginPerCell':
      'cv_aruco_detectorParameters_get_perspectiveRemoveIgnoredMarginPerCell',
  'cv_aruco_detectorParameters_get_perspectiveRemovePixelPerCell':
      'cv_aruco_detectorParameters_get_perspectiveRemovePixelPerCell',
  'cv_aruco_detectorParameters_get_polygonalApproxAccuracyRate':
      'cv_aruco_detectorParameters_get_polygonalApproxAccuracyRate',
  'cv_aruco_detectorParameters_set_adaptiveThreshConstant':
      'cv_aruco_detectorParameters_set_adaptiveThreshConstant',
  'cv_aruco_detectorParameters_set_adaptiveThreshWinSizeMax':
      'cv_aruco_detectorParameters_set_adaptiveThreshWinSizeMax',
  'cv_aruco_detectorParameters_set_adaptiveThreshWinSizeMin':
      'cv_aruco_detectorParameters_set_adaptiveThreshWinSizeMin',
  'cv_aruco_detectorParameters_set_adaptiveThreshWinSizeStep':
      'cv_aruco_detectorParameters_set_adaptiveThreshWinSizeStep',
  'cv_aruco_detectorParameters_set_aprilTagCriticalRad':
      'cv_aruco_detectorParameters_set_aprilTagCriticalRad',
  'cv_aruco_detectorParameters_set_aprilTagDeglitch': 'cv_aruco_detectorParameters_set_aprilTagDeglitch',
  'cv_aruco_detectorParameters_set_aprilTagMaxLineFitMse':
      'cv_aruco_detectorParameters_set_aprilTagMaxLineFitMse',
  'cv_aruco_detectorParameters_set_aprilTagMaxNmaxima': 'cv_aruco_detectorParameters_set_aprilTagMaxNmaxima',
  'cv_aruco_detectorParameters_set_aprilTagMinClusterPixels':
      'cv_aruco_detectorParameters_set_aprilTagMinClusterPixels',
  'cv_aruco_detectorParameters_set_aprilTagMinWhiteBlackDiff':
      'cv_aruco_detectorParameters_set_aprilTagMinWhiteBlackDiff',
  'cv_aruco_detectorParameters_set_aprilTagQuadDecimate':
      'cv_aruco_detectorParameters_set_aprilTagQuadDecimate',
  'cv_aruco_detectorParameters_set_aprilTagQuadSigma': 'cv_aruco_detectorParameters_set_aprilTagQuadSigma',
  'cv_aruco_detectorParameters_set_cornerRefinementMaxIterations':
      'cv_aruco_detectorParameters_set_cornerRefinementMaxIterations',
  'cv_aruco_detectorParameters_set_cornerRefinementMethod':
      'cv_aruco_detectorParameters_set_cornerRefinementMethod',
  'cv_aruco_detectorParameters_set_cornerRefinementMinAccuracy':
      'cv_aruco_detectorParameters_set_cornerRefinementMinAccuracy',
  'cv_aruco_detectorParameters_set_cornerRefinementWinSize':
      'cv_aruco_detectorParameters_set_cornerRefinementWinSize',
  'cv_aruco_detectorParameters_set_detectInvertedMarker':
      'cv_aruco_detectorParameters_set_detectInvertedMarker',
  'cv_aruco_detectorParameters_set_errorCorrectionRate':
      'cv_aruco_detectorParameters_set_errorCorrectionRate',
  'cv_aruco_detectorParameters_set_markerBorderBits': 'cv_aruco_detectorParameters_set_markerBorderBits',
  'cv_aruco_detectorParameters_set_maxErroneousBitsInBorderRate':
      'cv_aruco_detectorParameters_set_maxErroneousBitsInBorderRate',
  'cv_aruco_detectorParameters_set_maxMarkerPerimeterRate':
      'cv_aruco_detectorParameters_set_maxMarkerPerimeterRate',
  'cv_aruco_detectorParameters_set_minCornerDistanceRate':
      'cv_aruco_detectorParameters_set_minCornerDistanceRate',
  'cv_aruco_detectorParameters_set_minDistanceToBorder':
      'cv_aruco_detectorParameters_set_minDistanceToBorder',
  'cv_aruco_detectorParameters_set_minMarkerDistanceRate':
      'cv_aruco_detectorParameters_set_minMarkerDistanceRate',
  'cv_aruco_detectorParameters_set_minMarkerPerimeterRate':
      'cv_aruco_detectorParameters_set_minMarkerPerimeterRate',
  'cv_aruco_detectorParameters_set_minOtsuStdDev': 'cv_aruco_detectorParameters_set_minOtsuStdDev',
  'cv_aruco_detectorParameters_set_perspectiveRemoveIgnoredMarginPerCell':
      'cv_aruco_detectorParameters_set_perspectiveRemoveIgnoredMarginPerCell',
  'cv_aruco_detectorParameters_set_perspectiveRemovePixelPerCell':
      'cv_aruco_detectorParameters_set_perspectiveRemovePixelPerCell',
  'cv_aruco_detectorParameters_set_polygonalApproxAccuracyRate':
      'cv_aruco_detectorParameters_set_polygonalApproxAccuracyRate',
  'cv_aruco_drawDetectedCornersCharuco': 'cv_aruco_drawDetectedCornersCharuco',
  'cv_aruco_drawDetectedMarkers': 'cv_aruco_drawDetectedMarkers',
  'cv_aruco_estimatePoseCharucoBoard': 'cv_aruco_estimatePoseCharucoBoard',
  'cv_aruco_generateImageMarker': 'cv_aruco_generateImageMarker',
  'cv_aruco_getPredefinedDictionary': 'cv_aruco_getPredefinedDictionary',
  'cv_aruco_refineParameters_close': 'cv_aruco_refineParameters_close',
  'cv_aruco_refineParameters_create': 'cv_aruco_refineParameters_create',
  'cv_aruco_refineParameters_create_1': 'cv_aruco_refineParameters_create_1',
  'cv_aruco_refineParameters_get_checkAllOrders': 'cv_aruco_refineParameters_get_checkAllOrders',
  'cv_aruco_refineParameters_get_errorCorrectionRate': 'cv_aruco_refineParameters_get_errorCorrectionRate',
  'cv_aruco_refineParameters_get_minRepDistance': 'cv_aruco_refineParameters_get_minRepDistance',
  'cv_aruco_refineParameters_set_checkAllOrders': 'cv_aruco_refineParameters_set_checkAllOrders',
  'cv_aruco_refineParameters_set_errorCorrectionRate': 'cv_aruco_refineParameters_set_errorCorrectionRate',
  'cv_aruco_refineParameters_set_minRepDistance': 'cv_aruco_refineParameters_set_minRepDistance',
  'cv_freetype_FreeType2_close': 'cv_freetype_FreeType2_close',
  'cv_freetype_FreeType2_create': 'cv_freetype_FreeType2_create',
  'cv_freetype_FreeType2_getTextSize': 'cv_freetype_FreeType2_getTextSize',
  'cv_freetype_FreeType2_loadFontData': 'cv_freetype_FreeType2_loadFontData',
  'cv_freetype_FreeType2_loadFontData_buf': 'cv_freetype_FreeType2_loadFontData_buf',
  'cv_freetype_FreeType2_putText': 'cv_freetype_FreeType2_putText',
  'cv_freetype_FreeType2_setSplitNumber': 'cv_freetype_FreeType2_setSplitNumber',
  'cv_img_hash_BlockMeanHash_close': 'cv_img_hash_BlockMeanHash_close',
  'cv_img_hash_BlockMeanHash_compare': 'cv_img_hash_BlockMeanHash_compare',
  'cv_img_hash_BlockMeanHash_compute': 'cv_img_hash_BlockMeanHash_compute',
  'cv_img_hash_BlockMeanHash_create': 'cv_img_hash_BlockMeanHash_create',
  'cv_img_hash_BlockMeanHash_getMean': 'cv_img_hash_BlockMeanHash_getMean',
  'cv_img_hash_BlockMeanHash_setMode': 'cv_img_hash_BlockMeanHash_setMode',
  'cv_img_hash_averageHash_compare': 'cv_img_hash_averageHash_compare',
  'cv_img_hash_averageHash_compute': 'cv_img_hash_averageHash_compute',
  'cv_img_hash_colorMomentHash_compare': 'cv_img_hash_colorMomentHash_compare',
  'cv_img_hash_colorMomentHash_compute': 'cv_img_hash_colorMomentHash_compute',
  'cv_img_hash_marrHildrethHash_compare': 'cv_img_hash_marrHildrethHash_compare',
  'cv_img_hash_marrHildrethHash_compute': 'cv_img_hash_marrHildrethHash_compute',
  'cv_img_hash_pHash_compare': 'cv_img_hash_pHash_compare',
  'cv_img_hash_pHash_compute': 'cv_img_hash_pHash_compute',
  'cv_img_hash_radialVarianceHash_compare': 'cv_img_hash_radialVarianceHash_compare',
  'cv_img_hash_radialVarianceHash_compute': 'cv_img_hash_radialVarianceHash_compute',
  'cv_quality_QualityBRISQUE_close': 'cv_quality_QualityBRISQUE_close',
  'cv_quality_QualityBRISQUE_compute': 'cv_quality_QualityBRISQUE_compute',
  'cv_quality_QualityBRISQUE_computeFeatures_static': 'cv_quality_QualityBRISQUE_computeFeatures_static',
  'cv_quality_QualityBRISQUE_compute_static': 'cv_quality_QualityBRISQUE_compute_static',
  'cv_quality_QualityBRISQUE_create': 'cv_quality_QualityBRISQUE_create',
  'cv_quality_QualityGMSD_close': 'cv_quality_QualityGMSD_close',
  'cv_quality_QualityGMSD_compute': 'cv_quality_QualityGMSD_compute',
  'cv_quality_QualityGMSD_compute_static': 'cv_quality_QualityGMSD_compute_static',
  'cv_quality_QualityGMSD_create': 'cv_quality_QualityGMSD_create',
  'cv_quality_QualityMSE_close': 'cv_quality_QualityMSE_close',
  'cv_quality_QualityMSE_compute': 'cv_quality_QualityMSE_compute',
  'cv_quality_QualityMSE_compute_static': 'cv_quality_QualityMSE_compute_static',
  'cv_quality_QualityMSE_create': 'cv_quality_QualityMSE_create',
  'cv_quality_QualityPSNR_close': 'cv_quality_QualityPSNR_close',
  'cv_quality_QualityPSNR_compute': 'cv_quality_QualityPSNR_compute',
  'cv_quality_QualityPSNR_compute_static': 'cv_quality_QualityPSNR_compute_static',
  'cv_quality_QualityPSNR_create': 'cv_quality_QualityPSNR_create',
  'cv_quality_QualityPSNR_getMaxPixelValue': 'cv_quality_QualityPSNR_getMaxPixelValue',
  'cv_quality_QualityPSNR_setMaxPixelValue': 'cv_quality_QualityPSNR_setMaxPixelValue',
  'cv_quality_QualitySSIM_close': 'cv_quality_QualitySSIM_close',
  'cv_quality_QualitySSIM_compute': 'cv_quality_QualitySSIM_compute',
  'cv_quality_QualitySSIM_compute_static': 'cv_quality_QualitySSIM_compute_static',
  'cv_quality_QualitySSIM_create': 'cv_quality_QualitySSIM_create',
  'cv_wechat_qrcode_WeChatQRCode_close': 'cv_wechat_qrcode_WeChatQRCode_close',
  'cv_wechat_qrcode_WeChatQRCode_create': 'cv_wechat_qrcode_WeChatQRCode_create',
  'cv_wechat_qrcode_WeChatQRCode_create_1': 'cv_wechat_qrcode_WeChatQRCode_create_1',
  'cv_wechat_qrcode_WeChatQRCode_detectAndDecode': 'cv_wechat_qrcode_WeChatQRCode_detectAndDecode',
  'cv_wechat_qrcode_WeChatQRCode_getScaleFactor': 'cv_wechat_qrcode_WeChatQRCode_getScaleFactor',
  'cv_wechat_qrcode_WeChatQRCode_setScaleFactor': 'cv_wechat_qrcode_WeChatQRCode_setScaleFactor',
  'cv_ximgproc_EdgeBoxes_close': 'cv_ximgproc_EdgeBoxes_close',
  'cv_ximgproc_EdgeBoxes_create': 'cv_ximgproc_EdgeBoxes_create',
  'cv_ximgproc_EdgeBoxes_getAlpha': 'cv_ximgproc_EdgeBoxes_getAlpha',
  'cv_ximgproc_EdgeBoxes_getBeta': 'cv_ximgproc_EdgeBoxes_getBeta',
  'cv_ximgproc_EdgeBoxes_getBoundingBoxes': 'cv_ximgproc_EdgeBoxes_getBoundingBoxes',
  'cv_ximgproc_EdgeBoxes_getClusterMinMag': 'cv_ximgproc_EdgeBoxes_getClusterMinMag',
  'cv_ximgproc_EdgeBoxes_getEdgeMergeThr': 'cv_ximgproc_EdgeBoxes_getEdgeMergeThr',
  'cv_ximgproc_EdgeBoxes_getEdgeMinMag': 'cv_ximgproc_EdgeBoxes_getEdgeMinMag',
  'cv_ximgproc_EdgeBoxes_getEta': 'cv_ximgproc_EdgeBoxes_getEta',
  'cv_ximgproc_EdgeBoxes_getGamma': 'cv_ximgproc_EdgeBoxes_getGamma',
  'cv_ximgproc_EdgeBoxes_getKappa': 'cv_ximgproc_EdgeBoxes_getKappa',
  'cv_ximgproc_EdgeBoxes_getMaxAspectRatio': 'cv_ximgproc_EdgeBoxes_getMaxAspectRatio',
  'cv_ximgproc_EdgeBoxes_getMaxBoxes': 'cv_ximgproc_EdgeBoxes_getMaxBoxes',
  'cv_ximgproc_EdgeBoxes_getMinBoxArea': 'cv_ximgproc_EdgeBoxes_getMinBoxArea',
  'cv_ximgproc_EdgeBoxes_getMinScore': 'cv_ximgproc_EdgeBoxes_getMinScore',
  'cv_ximgproc_EdgeBoxes_setAlpha': 'cv_ximgproc_EdgeBoxes_setAlpha',
  'cv_ximgproc_EdgeBoxes_setBeta': 'cv_ximgproc_EdgeBoxes_setBeta',
  'cv_ximgproc_EdgeBoxes_setClusterMinMag': 'cv_ximgproc_EdgeBoxes_setClusterMinMag',
  'cv_ximgproc_EdgeBoxes_setEdgeMergeThr': 'cv_ximgproc_EdgeBoxes_setEdgeMergeThr',
  'cv_ximgproc_EdgeBoxes_setEdgeMinMag': 'cv_ximgproc_EdgeBoxes_setEdgeMinMag',
  'cv_ximgproc_EdgeBoxes_setEta': 'cv_ximgproc_EdgeBoxes_setEta',
  'cv_ximgproc_EdgeBoxes_setGamma': 'cv_ximgproc_EdgeBoxes_setGamma',
  'cv_ximgproc_EdgeBoxes_setKappa': 'cv_ximgproc_EdgeBoxes_setKappa',
  'cv_ximgproc_EdgeBoxes_setMaxAspectRatio': 'cv_ximgproc_EdgeBoxes_setMaxAspectRatio',
  'cv_ximgproc_EdgeBoxes_setMaxBoxes': 'cv_ximgproc_EdgeBoxes_setMaxBoxes',
  'cv_ximgproc_EdgeBoxes_setMinBoxArea': 'cv_ximgproc_EdgeBoxes_setMinBoxArea',
  'cv_ximgproc_EdgeBoxes_setMinScore': 'cv_ximgproc_EdgeBoxes_setMinScore',
  'cv_ximgproc_EdgeDrawing_close': 'cv_ximgproc_EdgeDrawing_close',
  'cv_ximgproc_EdgeDrawing_create': 'cv_ximgproc_EdgeDrawing_create',
  'cv_ximgproc_EdgeDrawing_detectEdges': 'cv_ximgproc_EdgeDrawing_detectEdges',
  'cv_ximgproc_EdgeDrawing_detectEllipses': 'cv_ximgproc_EdgeDrawing_detectEllipses',
  'cv_ximgproc_EdgeDrawing_detectLines': 'cv_ximgproc_EdgeDrawing_detectLines',
  'cv_ximgproc_EdgeDrawing_getEdgeImage': 'cv_ximgproc_EdgeDrawing_getEdgeImage',
  'cv_ximgproc_EdgeDrawing_getGradientImage': 'cv_ximgproc_EdgeDrawing_getGradientImage',
  'cv_ximgproc_EdgeDrawing_getParams': 'cv_ximgproc_EdgeDrawing_getParams',
  'cv_ximgproc_EdgeDrawing_getSegmentIndicesOfLines': 'cv_ximgproc_EdgeDrawing_getSegmentIndicesOfLines',
  'cv_ximgproc_EdgeDrawing_getSegments': 'cv_ximgproc_EdgeDrawing_getSegments',
  'cv_ximgproc_EdgeDrawing_setParams': 'cv_ximgproc_EdgeDrawing_setParams',
  'cv_ximgproc_GraphSegmentation_close': 'cv_ximgproc_GraphSegmentation_close',
  'cv_ximgproc_GraphSegmentation_create': 'cv_ximgproc_GraphSegmentation_create',
  'cv_ximgproc_GraphSegmentation_getK': 'cv_ximgproc_GraphSegmentation_getK',
  'cv_ximgproc_GraphSegmentation_getMinSize': 'cv_ximgproc_GraphSegmentation_getMinSize',
  'cv_ximgproc_GraphSegmentation_getSigma': 'cv_ximgproc_GraphSegmentation_getSigma',
  'cv_ximgproc_GraphSegmentation_processImage': 'cv_ximgproc_GraphSegmentation_processImage',
  'cv_ximgproc_GraphSegmentation_setK': 'cv_ximgproc_GraphSegmentation_setK',
  'cv_ximgproc_GraphSegmentation_setMinSize': 'cv_ximgproc_GraphSegmentation_setMinSize',
  'cv_ximgproc_GraphSegmentation_setSigma': 'cv_ximgproc_GraphSegmentation_setSigma',
  'cv_ximgproc_PeiLinNormalization': 'cv_ximgproc_PeiLinNormalization',
  'cv_ximgproc_RFFeatureGetter_clear': 'cv_ximgproc_RFFeatureGetter_clear',
  'cv_ximgproc_RFFeatureGetter_close': 'cv_ximgproc_RFFeatureGetter_close',
  'cv_ximgproc_RFFeatureGetter_create': 'cv_ximgproc_RFFeatureGetter_create',
  'cv_ximgproc_RFFeatureGetter_empty': 'cv_ximgproc_RFFeatureGetter_empty',
  'cv_ximgproc_RFFeatureGetter_getFeatures': 'cv_ximgproc_RFFeatureGetter_getFeatures',
  'cv_ximgproc_StructuredEdgeDetection_close': 'cv_ximgproc_StructuredEdgeDetection_close',
  'cv_ximgproc_StructuredEdgeDetection_computeOrientation':
      'cv_ximgproc_StructuredEdgeDetection_computeOrientation',
  'cv_ximgproc_StructuredEdgeDetection_create': 'cv_ximgproc_StructuredEdgeDetection_create',
  'cv_ximgproc_StructuredEdgeDetection_create_1': 'cv_ximgproc_StructuredEdgeDetection_create_1',
  'cv_ximgproc_StructuredEdgeDetection_detectEdges': 'cv_ximgproc_StructuredEdgeDetection_detectEdges',
  'cv_ximgproc_StructuredEdgeDetection_edgesNms': 'cv_ximgproc_StructuredEdgeDetection_edgesNms',
  'cv_ximgproc_anisotropicDiffusion': 'cv_ximgproc_anisotropicDiffusion',
  'cv_ximgproc_edgePreservingFilter': 'cv_ximgproc_edgePreservingFilter',
  'cv_ximgproc_findEllipses': 'cv_ximgproc_findEllipses',
  'cv_ximgproc_niBlackThreshold': 'cv_ximgproc_niBlackThreshold',
  'cv_ximgproc_rl_createRLEImage': 'cv_ximgproc_rl_createRLEImage',
  'cv_ximgproc_rl_dilate': 'cv_ximgproc_rl_dilate',
  'cv_ximgproc_rl_erode': 'cv_ximgproc_rl_erode',
  'cv_ximgproc_rl_getStructuringElement': 'cv_ximgproc_rl_getStructuringElement',
  'cv_ximgproc_rl_isRLMorphologyPossible': 'cv_ximgproc_rl_isRLMorphologyPossible',
  'cv_ximgproc_rl_morphologyEx': 'cv_ximgproc_rl_morphologyEx',
  'cv_ximgproc_rl_paint': 'cv_ximgproc_rl_paint',
  'cv_ximgproc_rl_threshold': 'cv_ximgproc_rl_threshold',
  'cv_ximgproc_thinning': 'cv_ximgproc_thinning',
  'cv_xobjdetect_WBDetector_close': 'cv_xobjdetect_WBDetector_close',
  'cv_xobjdetect_WBDetector_create': 'cv_xobjdetect_WBDetector_create',
  'cv_xobjdetect_WBDetector_detect': 'cv_xobjdetect_WBDetector_detect',
  'cv_xobjdetect_WBDetector_read': 'cv_xobjdetect_WBDetector_read',
  'cv_xobjdetect_WBDetector_train': 'cv_xobjdetect_WBDetector_train',
  'cv_xobjdetect_WBDetector_write': 'cv_xobjdetect_WBDetector_write',
};
