// coverage:ignore-file
// opencv_dart - OpenCV bindings for Dart language
//    License: Apache-2.0 https://github.com/hybridgroup/gocv/blob/release/LICENSE.txt
// Author: Rainyl
// License: Apache-2.0
// Date: 2024/01/28

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint

/// Mapping from Dart function name to native symbol name.
const recordUseMapping = {
  'cv_AlignMTB_close': 'cv_AlignMTB_close',
  'cv_AlignMTB_process': 'cv_AlignMTB_process',
  'cv_MergeMertens_close': 'cv_MergeMertens_close',
  'cv_MergeMertens_process': 'cv_MergeMertens_process',
  'cv_colorChange': 'cv_colorChange',
  'cv_createAlignMTB': 'cv_createAlignMTB',
  'cv_createAlignMTB_1': 'cv_createAlignMTB_1',
  'cv_createMergeMertens': 'cv_createMergeMertens',
  'cv_createMergeMertens_1': 'cv_createMergeMertens_1',
  'cv_detailEnhance': 'cv_detailEnhance',
  'cv_edgePreservingFilter': 'cv_edgePreservingFilter',
  'cv_fastNlMeansDenoising': 'cv_fastNlMeansDenoising',
  'cv_fastNlMeansDenoisingColored': 'cv_fastNlMeansDenoisingColored',
  'cv_fastNlMeansDenoisingColoredMulti': 'cv_fastNlMeansDenoisingColoredMulti',
  'cv_fastNlMeansDenoisingColoredMulti_1': 'cv_fastNlMeansDenoisingColoredMulti_1',
  'cv_fastNlMeansDenoisingColored_1': 'cv_fastNlMeansDenoisingColored_1',
  'cv_fastNlMeansDenoising_1': 'cv_fastNlMeansDenoising_1',
  'cv_illuminationChange': 'cv_illuminationChange',
  'cv_inpaint': 'cv_inpaint',
  'cv_pencilSketch': 'cv_pencilSketch',
  'cv_seamlessClone': 'cv_seamlessClone',
  'cv_stylization': 'cv_stylization',
  'cv_textureFlattening': 'cv_textureFlattening',
};
