name: Native Assets

on:
  push:
    branches: ["2.x"]
    tags:
      - "v2.*.*"
  pull_request:
    branches: ["2.x"]

jobs:
  build-android:
    name: build-android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: subosito/flutter-action@v2
        with:
          channel: "main"
      - run: |
          cd example/flutter
          flutter --version
          flutter config --enable-native-assets
          flutter pub get
          flutter build apk --release --target-platform android-arm64,android-arm,android-x64
      # - uses: actions/upload-artifact@v4
      #   name: upload-android-armeabi-v7a
      #   with:
      #     path: build/publish/libopencv_dart-android-armeabi-v7a.tar.gz
      #     name: libopencv_dart-android-armeabi-v7a.tar.gz

  build-ubuntu:
    name: build-ubuntu
    runs-on: ubuntu-latest

    steps:
      - name: setup
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: subosito/flutter-action@v2
        with:
          channel: "main"
      - uses: robinraju/release-downloader@v1.10
        with:
          repository: "rainyl/opencv_dart"
          tag: "dnn_test_files"
          fileName: "models.zip"
          out-file-path: "test/"
          extract: true
      - name: Run Test
        run: |
          dart pub get
          dart --enable-experiment=native-assets test -x skip-workflow

  build-windows:
    name: build-windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: subosito/flutter-action@v2
        with:
          channel: "main"
      - uses: robinraju/release-downloader@v1.10
        with:
          repository: "rainyl/opencv_dart"
          tag: "dnn_test_files"
          fileName: "models.zip"
          out-file-path: "test/"
          extract: true
      - name: Run Test
        run: |
          dart pub get
          dart --enable-experiment=native-assets test
  build-macos:
    name: build-macos
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: subosito/flutter-action@v2
        with:
          channel: "main"
      - uses: robinraju/release-downloader@v1.10
        with:
          repository: "rainyl/opencv_dart"
          tag: "dnn_test_files"
          fileName: "models.zip"
          out-file-path: "test/"
          extract: true
      - name: Run Test
        run: |
          dart pub get
          dart --enable-experiment=native-assets test -x skip-workflow
  build-ios:
      name: build-ios
      runs-on: macos-latest
      steps:
        - uses: actions/checkout@v4
          with:
            submodules: true
        - name: Set up Flutter
          uses: subosito/flutter-action@v2
          with:
            channel: main # or: beta, master (or main)
        - name: build
          run: |
            cd example/flutter
            flutter config --enable-native-assets
            flutter build ios --release --no-codesign
