name: build and test

on:
  push:
    branches: ["main", "dnn-test"]
  pull_request:
    branches: [ "main" ]

jobs:
  build-windows:
    name: build-windows
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - uses: robinraju/release-downloader@v1.10
        with:
          repository: "rainyl/opencv_dart"
          tag: "dnn_test_files"
          fileName: "models.zip"
          out-file-path: "test/"
          extract: true
      - name: build-opencv-dart
        run: |
          ls test
          ls test/models
          python3 -m pip install conan
          conan profile detect -f
          conan build . -b missing -s compiler.cppstd=20

      - uses: actions/upload-artifact@v4
        name: upload-windows-x64
        with:
          path: build/publish/libopencv_dart-windows-x64.tar.gz
          name: libopencv_dart-windows-x64.tar.gz
      - uses: subosito/flutter-action@v2
        with:
          # flutter-version: '3.16.9'
          channel: "stable"
      - name: setup coverage
        run: |
          cd "${{github.workspace}}"
          $env:PATH = "${{github.workspace}}\windows;${env:PATH}"
          dart pub global activate coverage
          dart pub global run coverage:test_with_coverage --package . --package-name opencv_dart
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: rainyl/opencv_dart
          file: ./coverage/lcov.info
