name: Examples

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-windows:
    name: build-windows
    runs-on: windows-2019
    steps:
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'
          channel: "stable"
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: build
        run: |
          cd example
          flutter build windows
          # flutter build apk --release --target-platform android-arm64,android-arm,android-x64 --split-per-abi
  build-ubuntu:
    name: build-ubuntu
    runs-on: ubuntu-latest

    steps:
      - name: setup
        run: |
          sudo apt-get update
          sudo apt-get install -y curl git wget python3 unzip build-essential \
            libgtk-3-dev ffmpeg libavcodec-dev \
            cmake ninja-build nasm libavformat-dev libavutil-dev \
            libswscale-dev libgflags-dev \
            libjpeg-dev libpng-dev libtiff-dev python3-pip
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'
          channel: "stable"
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: build
        run: |
          cd example
          flutter build linux
          flutter build apk --release --target-platform android-arm64,android-arm,android-x64 --split-per-abi
  build-macos:
    name: build-macos
    runs-on: macos-13
    steps:
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'
          channel: "stable"
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: build
        run: |
          cd example
          flutter build macos
          # flutter build apk --release --target-platform android-arm64,android-arm,android-x64 --split-per-abi
          flutter build ios --release --no-codesign
  build-macos-arm:
    name: build-macos-arm
    runs-on: macos-14
    steps:
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'
          channel: "stable"
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: build
        run: |
          cd example
          flutter build macos
          # flutter build apk --release --target-platform android-arm64,android-arm,android-x64 --split-per-abi
          flutter build ios --release --no-codesign
