on:
  push:

name: Format Code

jobs:
  build:
    name: format code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: main # or: beta, master (or main)
      - name: Format code
        run: |
          cd packages/dartcv
          dart format .
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "dart format ✅"
          branch: ${{ github.head_ref }}
