name: Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: [ "main" ]

jobs:
  test-windows:
    name: test-windows
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: subosito/flutter-action@v2
        with:
          # flutter-version: '3.16.9'
          channel: "stable"
      - name: Run Test
        run: |
          dart run opencv_dart:setup windows -a x64
          $env:PATH = "${{github.workspace}}\windows;${env:PATH}"
          flutter pub get
          flutter test -x no-local-files
      - name: setup coverage
        run: |
          $env:PATH = "${{github.workspace}}\windows;${env:PATH}"
          dart pub global activate coverage
          dart pub global run coverage:test_with_coverage
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: rainyl/opencv_dart
          file: ./coverage/lcov.info
