name: Test Macos x64

on:
  push:
    branches: ["fix-macos-x64"]

env:
  ANDROID_NDK_VERSION: r26c
  OPENCV_VERSION: 4.9.0
  LIB_NAME: libopencv_dart

jobs:
  build-macos:
    name: build-macos
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: setup
        run: |
          brew install --force --overwrite ninja ccache ffmpeg@6 nasm conan
          brew link --overwrite ffmpeg@6
          echo 'export PATH="/usr/local/opt/ffmpeg@6/bin:$PATH"' >> /Users/runner/.bash_profile
          export LDFLAGS="-L/usr/local/opt/ffmpeg@6/lib"
          export CPPFLAGS="-I/usr/local/opt/ffmpeg@6/include"
          conan profile detect -f
          cd ${{github.workspace}}
      - name: build
        run: |
          conan build . -b missing \
          -o output_dir="build/macos/x64"

      - uses: actions/upload-artifact@v4
        name: upload-macos-x64
        with:
          path: build/publish/libopencv_dart-macos-x64.tar.gz
          name: libopencv_dart-macos-x64.tar.gz
      - uses: subosito/flutter-action@v2
        with:
          # flutter-version: '3.16.9'
          channel: "stable"
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          prerelease: false
          files: |
            build/publish/libopencv_dart-macos-x64.tar.gz
      - name: Run Test
        run: |
          ls -alh ${{github.workspace}}/macos
          export DYLD_LIBRARY_PATH="${{github.workspace}}/macos:$DYLD_LIBRARY_PATH"
          dart pub get
          dart test -x skip-workflow,no-local-files
  build-macos-arm64:
    name: build-macos-arm64
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: setup
        run: |
          # brew update
          brew install --force --overwrite ninja ccache ffmpeg@6 nasm conan
          brew link --overwrite ffmpeg@6
          conan profile detect -f
          cd ${{github.workspace}}
      - name: build
        run: |
          conan build . -b missing \
          -o output_dir="build/macos/arm64"

      - uses: actions/upload-artifact@v4
        name: upload-macos-arm64
        with:
          path: build/publish/libopencv_dart-macos-arm64.tar.gz
          name: libopencv_dart-macos-arm64.tar.gz
      - uses: subosito/flutter-action@v2
        with:
          # flutter-version: '3.16.9'
          channel: "stable"
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          prerelease: false
          files: |
            build/publish/libopencv_dart-macos-arm64.tar.gz
      - name: Run Test
        run: |
          ls -alh ${{github.workspace}}/macos
          export DYLD_LIBRARY_PATH="${{github.workspace}}/macos:$DYLD_LIBRARY_PATH"
          dart pub get
          dart test -x skip-workflow,no-local-files
